apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.ServicePort }}
    protocol: TCP
    targetPort: {{ .Values.ServicePort }}
  selector:
    app: nginx
    tag: alpine
  type: {{ .Values.ServiceType }}
